### ISSUE TITLE
Incorrect Spelling of Documents

### ISSUE THREAD

**Issue by theinhumaneme** [RickyDane/rdpFX#4]
https://github.com/RickyDane/rdpFX/blob/db57fa0f245ddf68627ef08726f7b461d8281d58/ui/index.html#L56

Hey, coming here from your reddit post, amazing tool, here is an error that I found, just wanted to let you know :D

**Comment by RickyDane** [comment]
Hey, good eyes! I'll correct immediately!

**Comment by theinhumaneme** [comment]
😄
