### ISSUE TITLE
Miller Column View

### ISSUE THREAD

**Issue by the-arkhive** [RickyDane/rdpFX#57]
I actually just found this project in a reddit post where miller column view was mentioned. I'm on a brand new linux install and I'm looking for a modern, performant, file manager, ideally with miller column view. I'm going to install this for now, and look into working on adding the feature myself, but wanted to open this as a place for other people to chime in. It seemed there was a handful of folks interested in this feature on the reddit post.

**Comment by RickyDane** [comment]
In fact, some people were interested in miller columns, but I haven't added this view yet because it is one of the less popular ones. I will dig into it when I have some free time and try to implement the view.

**Comment by RickyDane** [comment]
@the-arkhive
I just finished the first version for the miller columns and the packages are being build right now.
You can test the new release, but keep in mind that this is a very very very early pre-release but I think you can test it enough to know, if that is what you wanted.

I will continue the development on miller columns and for example try to make drag n drop working across panels

**Comment by RickyDane** [comment]
Implemented drag and drop onto folders for any view.
Closing with #60
