### ISSUE TITLE
Installer is not working on Mac M1 Pro

### ISSUE THREAD

**Issue by MyCADDev** [RickyDane/rdpFX#78]
I tried installing rdpFX_0.4.4_aarch64.dmg - fails with message saying file is corrupt.

**Comment by RickyDane** [comment]
I will look into it, as soon as I have the time. That's high on my priority list!

**Comment by RickyDane** [comment]
I quickly checked my local arm build installer and it works but after I upload it to github and download it, its "corrupted".
That's a weird behavior. I will need to fix this.

**Comment by RickyDane** [comment]
Hey @MyCADDev, I just built a new universal version of rdpFX and it looks like it works now!
I don't know why it wouldn't work as a native arm or intel version, but I think a universal version is acceptable for now.
Could you try it on your end, if it works?

**Comment by RickyDane** [comment]
If it's not working with a built version, try it with the following command: xattr -d "path/to/app".

**Comment by RickyDane** [comment]
If this issue still comes up, here is another solution:

If macOS is reporting that this file can't be opened:

![Screenshot 2024-08-06 at 22 07 53](https://github.com/user-attachments/assets/7a55e9f9-2e13-46cd-ba31-74e687249ace)

Navigate into you system settings -> privacy and security, scroll to the bottom and click open anyway:

![Screenshot 2024-08-06 at 22 09 00](https://github.com/user-attachments/assets/07341da7-bbea-4bd6-b6a3-cdf323e26e08)
